version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name: sample_app
    volumes:
      - ./:/go
    tty: true
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: sample_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"